name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        name: unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn --frozen-lockfile
            - name: unit tests
              run: yarn test:ci
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: unit test results
                  path: test-result-unittests.json
                  reporter: jest-junit
