name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        name: unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: install yarn
              run: npm install -g yarn@3.6.1
            - name: install dependencies
              run: yarn --frozen-lockfile
            - name: run unit tests
              run: yarn test:ci
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: unit test results
                  path: junit.xml
                  reporter: jest-junit
